#!/bin/sh
cd GameBoy/Debug
./GameBoy BROKER CATCH_POKEMON Pikachu 9 3
./GameBoy BROKER CATCH_POKEMON Squirtle 9 3

./GameBoy BROKER CAUGHT_POKEMON 10 OK
./GameBoy BROKER CAUGHT_POKEMON 11 FAIL

./GameBoy BROKER CATCH_POKEMON Bulbasaur 1 7
./GameBoy BROKER CATCH_POKEMON Charmander 1 7

./GameBoy BROKER GET_POKEMON Pichu
./GameBoy BROKER GET_POKEMON Raichu
