#!/bin/sh
./GameBoy TEAM APPEARED_POKEMON Jolteon 2 2
./GameBoy TEAM APPEARED_POKEMON Flareon 4 6
./GameBoy TEAM APPEARED_POKEMON Umbreon 10 6
./GameBoy TEAM APPEARED_POKEMON Espeon 7 1
./GameBoy TEAM APPEARED_POKEMON Vaporeon 4 10
